_target_: src.datamodules.SemanticDataModule

repo: spaicom-lab
name: semantic-cifar10

attributes:
  - label

batch_size: 64
num_workers: 4

val_split: 0.1
test_split: 0.1
pilot_split: 0.0
pilot_num_samples: null
comm_data: private_pilots
seed: ${seed}
mode: min_size
