defaults:
  - hetero_cifar10_overlap_experiment
  - _self_

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      orchestrator: sheaf_frl,sheaf_fmtl,federated,dpsgd,dfedu,non_cooperative
      dataset.shared_classes: 2,4,6,8,10
