defaults:
  - dataset: cifar10
  - model: timm_classifier
  - orchestrator: sheaf_frl
  - optimizer: sgd
  - _self_

seed: 42

agent_rotations:
  0: 0
  1: 90

agent_classes:
  0: null
  1: null

agents:
  0:
    model_name: convnext_tiny.in12k
    pretrained: false
  1:
    model_name: convnext_small.in12k
    pretrained: false

graph:
  neighbors_mode: "fully_connected"
  seed: 42
  p: 0.3
  m: 3

model:
  decoder_hidden_dims: [256]
  dropout: 0.1
  use_batchnorm: true

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: sheaf-repr-learning__cnn-agents-exp
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  log_model: false

trainer:
  max_epochs: 50
  accelerator: auto
  devices: 1

  deterministic: true
  num_sanity_val_steps: 2
  log_every_n_steps: 50

callbacks:
  lr_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: step

  checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: validation/global_task_performance_epoch
    mode: max
    save_top_k: 1
    save_last: true

  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: validation/global_task_performance_epoch
    patience: 5
    mode: max

  #batch_size_finder:
  #  _target_: lightning.pytorch.callbacks.BatchSizeFinder
  #  mode: power
  #  init_val: 32
  #  max_trials: 5
