repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.9
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: test-fast
        name: test-fast
        entry: just test_fast
        language: system
        pass_filenames: false
        always_run: false
