_target_: src.datamodules.SemanticDataModule

repo: spaicom-lab
name: semantic-cifar10

models:
  - aimv2_1b_patch14_224.apple_pt
  - aimv2_1b_patch14_336.apple_pt

attributes:
  - label

batch_size: 64
num_workers: 4

val_split: 0.1
test_split: 0.1
seed: 42
mode: min_size
