agents:
  0:
    _target_: src.agents.CNNClassifier
    encoder_hidden_dims: [16, 32, 64]
    decoder_hidden_dims: [32, 16]
    dropout: 0.3
    use_batchnorm: true
  1:
    _target_: src.agents.CNNClassifier
    encoder_hidden_dims: [32, 64]
    decoder_hidden_dims: [32]
    dropout: 0.1
    use_batchnorm: true
