agents:
  0:
    _target_: src.agents.CNNClassifier
    encoder_hidden_dims: [1, 2, 4]
    decoder_hidden_dims: [2, 1]
    dropout: 0.3
    use_batchnorm: true
  1:
    _target_: src.agents.CNNClassifier
    encoder_hidden_dims: [2, 4]
    decoder_hidden_dims: [2]
    dropout: 0.1
    use_batchnorm: true
